// Command docgen writes the generated parts of the documentation into docs/generated/:
//
//	step-anatomy.html  the figure on "Pricing a step", computed by this kernel
//	divergences.md     every note in the source headed KNOWN DIVERGENCE, KNOWN over-charge
//	                   or COVERAGE LIMIT, with where it is
//	sources.md         the versions and commits the kernel's behavior and inputs are pinned to
//
// Run it after changing the cost model, a marked note, or a pin, and commit what it writes:
//
//	go run ./internal/docgen
//
// TestGeneratedDocsAreCurrent fails while a committed file differs from what this would write.
// It needs the fetched catalog and registry (scripts/fetch-testdata.sh), because the figure is
// priced from them.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"math"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/inference-sim/blis-schemas/kernel"

	latencykernel "github.com/inference-sim/blis-latency-kernel"
	"github.com/inference-sim/blis-latency-kernel/internal/harness"
)

const repoURL = "https://github.com/inference-sim/blis-latency-kernel"

func main() {
	root := repoRoot()
	files, err := generate(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
	dir := filepath.Join(root, "docs", "generated")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "docgen:", err)
		os.Exit(1)
	}
	for name, body := range files {
		if err := os.WriteFile(filepath.Join(dir, name), body, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "docgen:", err)
			os.Exit(1)
		}
	}
}

// repoRoot is the repository root: the parent of the scenarios directory harness resolves.
func repoRoot() string { return filepath.Dir(harness.DefaultScenarios()) }

// generate returns every generated file, by name.
func generate(root string) (map[string][]byte, error) {
	step, err := stepAnatomy()
	if err != nil {
		return nil, fmt.Errorf("step-anatomy.html: %w", err)
	}
	div, err := divergences(root)
	if err != nil {
		return nil, fmt.Errorf("divergences.md: %w", err)
	}
	src, err := sources(root)
	if err != nil {
		return nil, fmt.Errorf("sources.md: %w", err)
	}
	return map[string][]byte{
		"step-anatomy.html": step,
		"divergences.md":    div,
		"sources.md":        src,
	}, nil
}

const generatedNote = "Generated by `go run ./internal/docgen`; do not edit by hand."

// ---------------------------------------------------------------------------------------------
// The step figure.

// figureScenario is the deployment the figure prices, a committed scenario.
const (
	figureScenario = "aisimulate/deepseek-v3-h200-fp8-sglang-tp8.yaml"
	figureContext  = 4096
)

var figureBatches = []float64{1, 2, 4, 8, 16, 32, 64, 128, 256}

// The resources the left panel draws, in the order their labels are read.
var figureResources = []struct {
	r     kernel.Resource
	name  string
	class string
}{
	{kernel.ResourceHBM, "HBM", "s-hbm"},
	{kernel.ResourceSM, "SM", "s-sm"},
	{kernel.ResourceNVLink, "NVLink", "s-nvlink"},
	{kernel.ResourceNIC, "NIC", "s-nic"},
	{kernel.ResourceHost, "host", "s-host"},
}

func resourceName(r kernel.Resource) string {
	for _, f := range figureResources {
		if f.r == r {
			return f.name
		}
	}
	return string(r)
}

func stepAnatomy() ([]byte, error) {
	in, err := latencykernel.OpenInputs(figureScenario, harness.DefaultRepos(), 0)
	if err != nil {
		return nil, err
	}
	k, err := latencykernel.New(in)
	if err != nil {
		return nil, err
	}
	ms := func(d interface{ Seconds() float64 }) float64 { return d.Seconds() * 1e3 }

	per := map[kernel.Resource][]float64{}
	var overlap, noOverlap []float64
	var bottleneck []kernel.Resource
	for _, n := range figureBatches {
		e := k.StepTime(harness.DecodeBatch(int(n), figureContext))
		for _, f := range figureResources {
			per[f.r] = append(per[f.r], ms(e.PerResource[f.r]))
		}
		overlap = append(overlap, ms(e.Overlap))
		noOverlap = append(noOverlap, ms(e.NoOverlap))
		bottleneck = append(bottleneck, e.Bottleneck)
	}

	maxOf := func(vs []float64) float64 {
		m := 0.0
		for _, v := range vs {
			m = max(m, v)
		}
		return m
	}
	// Both panels share one vertical scale, so NoOverlap on the right reads as the sum of
	// the lines on the left.
	const width, height = 760.0, 350.0
	yMax := niceCeiling(maxOf(noOverlap), 10)
	left := panel{x: 52, y: 72, w: 250, h: 220, xs: figureBatches, yMax: yMax, yStep: 10,
		yUnit: "ms", title: "Time on each resource",
		xLabel: "requests in the batch (log scale)"}
	right := panel{x: 452, y: 72, w: 220, h: 220, xs: figureBatches, yMax: yMax, yStep: 10,
		yUnit: "ms", title: "The step's two estimates",
		xLabel: "requests in the batch (log scale)"}

	var b strings.Builder
	fmt.Fprintf(&b, "<!-- %s -->\n", generatedNote)
	b.WriteString(`<figure class="diagram chart" markdown="0">` + "\n")
	fmt.Fprintf(&b, `<svg viewBox="0 0 %.0f %.0f" role="img" aria-labelledby="fig-step-title fig-step-desc">`+"\n",
		width, height)
	b.WriteString(`<title id="fig-step-title">Where a decode step's time goes, by batch size</title>` + "\n")
	fmt.Fprintf(&b, `<desc id="fig-step-desc">%s</desc>`+"\n", stepDescription(in, per, overlap, noOverlap, bottleneck))

	left.axes(&b)
	// Where the bottleneck changes: a rule between the two batch sizes, each side named
	// above the plot, where no data or tick can be.
	for i := 1; i < len(bottleneck); i++ {
		if bottleneck[i] == bottleneck[i-1] {
			continue
		}
		x := (left.px(figureBatches[i-1]) + left.px(figureBatches[i])) / 2
		fmt.Fprintf(&b, `<line class="rule" x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f"/>`+"\n",
			x, left.y-28, x, left.y+left.h)
		fmt.Fprintf(&b, `<text class="note" x="%.1f" y="%.1f" text-anchor="end">%s-bound</text>`+"\n",
			x-5, left.y-18, resourceName(bottleneck[i-1]))
		fmt.Fprintf(&b, `<text class="note" x="%.1f" y="%.1f">%s-bound</text>`+"\n",
			x+5, left.y-18, resourceName(bottleneck[i]))
	}
	var labels []endLabel
	for _, f := range figureResources {
		ys := per[f.r]
		if maxOf(ys) <= 0 {
			continue
		}
		left.line(&b, f.class, ys)
		labels = append(labels, endLabel{text: f.name, class: f.class, y: ys[len(ys)-1]})
	}
	left.endLabels(&b, labels)

	right.axes(&b)
	right.band(&b, "band", overlap, noOverlap)
	right.line(&b, "s-nooverlap", noOverlap)
	right.line(&b, "s-overlap", overlap)
	right.endLabels(&b, []endLabel{
		{text: "NoOverlap", class: "s-nooverlap", y: noOverlap[len(noOverlap)-1]},
		{text: "Overlap", class: "s-overlap", y: overlap[len(overlap)-1]},
	})
	b.WriteString("</svg>\n")
	fmt.Fprintf(&b, "<figcaption>%s</figcaption>\n", stepCaption(in, per, overlap, noOverlap, bottleneck))
	b.WriteString("</figure>\n")
	return []byte(b.String()), nil
}

// deploymentPhrase names the figure's deployment from the documents it was priced from, the
// model by its catalog name.
func deploymentPhrase(in latencykernel.Inputs, model string) string {
	pool := in.Deployment.Pools[in.PoolIndex]
	gpus := max(pool.Parallel.TP, 1) * max(pool.Parallel.DP, 1)
	return fmt.Sprintf("The model %s, served in %s on %d %s GPUs at tensor-parallel width %d",
		model, pool.Engine.Quantization, gpus, strings.ToUpper(in.Chip.Name),
		max(pool.Parallel.TP, 1))
}

// spans describes where each resource is the bottleneck, as runs of batch sizes.
func spans(bottleneck []kernel.Resource) string {
	var parts []string
	start := 0
	for i := 1; i <= len(bottleneck); i++ {
		if i < len(bottleneck) && bottleneck[i] == bottleneck[start] {
			continue
		}
		lo, hi := figureBatches[start], figureBatches[i-1]
		rng := fmt.Sprintf("%g to %g requests", lo, hi)
		if lo == hi {
			rng = fmt.Sprintf("%g request", lo)
			if lo != 1 {
				rng += "s"
			}
		}
		parts = append(parts, fmt.Sprintf("%s from %s", resourceName(bottleneck[start]), rng))
		start = i
	}
	if len(parts) == 1 {
		return parts[0]
	}
	return strings.Join(parts[:len(parts)-1], ", ") + " and " + parts[len(parts)-1]
}

func stepDescription(in latencykernel.Inputs, per map[kernel.Resource][]float64,
	overlap, noOverlap []float64, bottleneck []kernel.Resource) string {
	return fmt.Sprintf("Two panels against the number of requests in a decode batch, from 1 to "+
		"256 on a log scale, each request decoding one token against a %d-token context. %s. "+
		"Left: the time each resource needs over the step. Right, on the same scale: the "+
		"Overlap and NoOverlap estimates, which run from %.1f and %.1f ms at one request to "+
		"%.1f and %.1f ms at 256. The bottleneck is %s.",
		figureContext, deploymentPhrase(in, in.Model.Name), overlap[0], noOverlap[0],
		overlap[len(overlap)-1], noOverlap[len(noOverlap)-1], spans(bottleneck))
}

func stepCaption(in latencykernel.Inputs, per map[kernel.Resource][]float64,
	overlap, noOverlap []float64, bottleneck []kernel.Resource) string {
	last := len(figureBatches) - 1
	var notes []string
	// A bottleneck decided by a hair should say so, since the lines are indistinguishable.
	type ranked struct {
		name string
		ms   float64
	}
	var first []ranked
	for _, f := range figureResources {
		first = append(first, ranked{f.name, per[f.r][0]})
	}
	sort.Slice(first, func(i, j int) bool { return first[i].ms > first[j].ms })
	if gap := (first[0].ms - first[1].ms) / first[0].ms; gap < 0.05 {
		notes = append(notes, fmt.Sprintf("At one request %s and %s are within %.0f%% of each "+
			"other (%.2f and %.2f ms), so their lines coincide there.", first[0].name,
			first[1].name, math.Ceil(gap*100), first[0].ms, first[1].ms))
	}
	var nic float64
	for _, v := range per[kernel.ResourceNIC] {
		nic = max(nic, v)
	}
	if nic == 0 {
		notes = append(notes, "No collective leaves the node, so NIC carries nothing and is "+
			"not drawn.")
	}
	return fmt.Sprintf("%s (<code>testdata/%s</code>), every request decoding one token against "+
		"a %s-token context. <b>Left:</b> the time each resource needs over one step. The "+
		"bottleneck, the resource with the most time, is %s. %s <b>Right:</b> the step's two "+
		"estimates, on the same scale: NoOverlap is the sum of the lines on the left, and "+
		"Overlap lets each layer's resources work at once. Going from one request to %g "+
		"multiplies the step by about %.0f, and divides the time per request by about %.0f. "+
		"Computed by this kernel at batch sizes that are powers of two, joined by straight lines.",
		deploymentPhrase(in, "<code>"+in.Model.Name+"</code>"), figureScenario,
		thousands(figureContext), spans(bottleneck), strings.Join(notes, " "),
		figureBatches[last], noOverlap[last]/noOverlap[0],
		(noOverlap[0])/(noOverlap[last]/figureBatches[last]))
}

func thousands(n int) string {
	s := fmt.Sprint(n)
	if len(s) <= 3 {
		return s
	}
	return s[:len(s)-3] + "," + s[len(s)-3:]
}

// ---------------------------------------------------------------------------------------------
// The marked notes.

var marker = regexp.MustCompile(`KNOWN DIVERGENCE|KNOWN over-charge|COVERAGE LIMIT`)

type note struct {
	file, decl, heading, text string
	pos                       int
}

func divergences(root string) ([]byte, error) {
	var notes []note
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(root, path)
		if d.IsDir() {
			switch {
			case strings.HasPrefix(d.Name(), ".") && rel != ".", d.Name() == "testdata",
				d.Name() == "docs", rel == filepath.Join("internal", "docgen"):
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		found, err := notesIn(path, filepath.ToSlash(rel))
		notes = append(notes, found...)
		return err
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(notes, func(i, j int) bool {
		if notes[i].file != notes[j].file {
			return notes[i].file < notes[j].file
		}
		return notes[i].pos < notes[j].pos
	})

	// Every note needs a summary, and every summary a note.
	used := map[string]bool{}
	for _, n := range notes {
		if used[n.key()] {
			return nil, fmt.Errorf("two %s notes in %s in %s; give one its own declaration "+
				"or extend the key", n.heading, n.decl, n.file)
		}
		used[n.key()] = true
		if _, ok := summaries[n.key()]; !ok {
			return nil, fmt.Errorf("the %s note in %s in %s has no summary; add %q to "+
				"internal/docgen/summaries.go", n.heading, n.decl, n.file, n.key())
		}
	}
	for key := range summaries {
		if !used[key] {
			return nil, fmt.Errorf("internal/docgen/summaries.go has a summary for %q, and "+
				"there is no such note", key)
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "<!-- %s -->\n\n", generatedNote)
	// The kinds in use, defined once above the notes.
	var kinds []string
	for _, k := range noteKinds {
		for _, n := range notes {
			if n.heading == k.heading {
				kinds = append(kinds, k.heading)
				fmt.Fprintf(&b, "%s\n:   %s\n\n", k.heading, k.meaning)
				break
			}
		}
	}
	for _, n := range notes {
		s := summaries[n.key()]
		fmt.Fprintf(&b, "### %s\n\n", s.title)
		fmt.Fprintf(&b, "*%s, in `%s` in [`%s`](%s/blob/main/%s).*\n\n",
			n.heading, n.decl, n.file, repoURL, n.file)
		fmt.Fprintf(&b, "%s\n\n", s.summary)
		b.WriteString("??? quote \"The note in the source\"\n")
		for _, line := range strings.Split(n.text, "\n") {
			if line == "" {
				b.WriteString("\n")
				continue
			}
			fmt.Fprintf(&b, "    %s\n", markdownEscaper.Replace(line))
		}
		b.WriteString("\n")
	}
	fmt.Fprintf(&b, "*%d notes: %s.*\n", len(notes), countKinds(notes, kinds))
	return []byte(b.String()), nil
}

// noteKinds are the kinds of marked note, in the order the page defines them.
var noteKinds = []struct{ heading, meaning string }{
	{"Known divergence", "The engine does something the kernel prices differently on purpose."},
	{"Known over-charge", "A term the kernel knows is charged too high, kept because removing " +
		"it makes the measured accuracy worse. The note records the measurement."},
	{"Coverage limit", "Engine behavior the kernel does not model, with what it charges " +
		"instead."},
}

func countKinds(notes []note, kinds []string) string {
	var parts []string
	for _, k := range kinds {
		n := 0
		for _, x := range notes {
			if x.heading == k {
				n++
			}
		}
		parts = append(parts, fmt.Sprintf("%d %s", n, strings.ToLower(k)))
		if n != 1 {
			parts[len(parts)-1] += "s"
		}
	}
	return strings.Join(parts, ", ")
}

func (n note) key() string { return n.file + "|" + n.decl + "|" + n.heading }

// markdownEscaper keeps a source comment literal when it is quoted on a page: an identifier
// such as _quantize_and_setup_dispatch must not become emphasis, nor a bracket a link.
var markdownEscaper = strings.NewReplacer(`\`, `\\`, "*", `\*`, "_", `\_`, "`", "\\`",
	"[", `\[`, "]", `\]`, "<", "&lt;", ">", "&gt;")

// notesIn returns the marked paragraphs of one file, each with the declaration it is in.
func notesIn(path, rel string) ([]note, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}
	var out []note
	for _, cg := range f.Comments {
		text := cg.Text()
		for _, para := range strings.Split(text, "\n\n") {
			loc := marker.FindStringIndex(para)
			// A mention that points back to a note ("the KNOWN over-charge above") is not
			// itself one.
			if loc == nil || strings.HasSuffix(strings.TrimSpace(para[:loc[0]]), "the") {
				continue
			}
			heading := "Coverage limit"
			if m := para[loc[0]:loc[1]]; strings.HasPrefix(m, "KNOWN") {
				heading = "Known over-charge"
				if m == "KNOWN DIVERGENCE" {
					heading = "Known divergence"
				}
			}
			out = append(out, note{
				file: rel, decl: enclosing(f, cg.Pos()), heading: heading,
				text: strings.TrimRight(para, "\n"), pos: int(cg.Pos()),
			})
		}
	}
	return out, nil
}

// enclosing names the declaration a comment documents or sits inside.
func enclosing(f *ast.File, pos token.Pos) string {
	for _, d := range f.Decls {
		var docStart token.Pos = d.Pos()
		switch d := d.(type) {
		case *ast.FuncDecl:
			if d.Doc != nil {
				docStart = d.Doc.Pos()
			}
			if pos >= docStart && pos <= d.End() {
				if d.Recv != nil && len(d.Recv.List) > 0 {
					return fmt.Sprintf("(%s).%s", exprString(d.Recv.List[0].Type), d.Name.Name)
				}
				return d.Name.Name
			}
		case *ast.GenDecl:
			if d.Doc != nil {
				docStart = d.Doc.Pos()
			}
			if pos >= docStart && pos <= d.End() {
				for _, s := range d.Specs {
					switch s := s.(type) {
					case *ast.ValueSpec:
						return s.Names[0].Name
					case *ast.TypeSpec:
						return s.Name.Name
					}
				}
			}
		}
	}
	return "package " + f.Name.Name
}

func exprString(e ast.Expr) string {
	switch e := e.(type) {
	case *ast.StarExpr:
		return "*" + exprString(e.X)
	case *ast.Ident:
		return e.Name
	}
	return "?"
}

// ---------------------------------------------------------------------------------------------
// The pins.

func sources(root string) ([]byte, error) {
	gomod, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		return nil, err
	}
	schemas := ""
	for _, line := range strings.Split(string(gomod), "\n") {
		// Either form: inside a require block, or a single `require` line.
		f := strings.Fields(strings.TrimPrefix(strings.TrimSpace(line), "require "))
		if len(f) >= 2 && f[0] == "github.com/inference-sim/blis-schemas" {
			schemas = f[1]
		}
	}
	if schemas == "" {
		return nil, fmt.Errorf("go.mod requires no github.com/inference-sim/blis-schemas")
	}
	lock, err := os.ReadFile(filepath.Join(root, "testdata", "upstream.lock"))
	if err != nil {
		return nil, err
	}
	type pin struct{ what, version, commit, where string }
	pins := []pin{
		{"Engine behavior: [vLLM](https://github.com/vllm-project/vllm/tree/v" +
			latencykernel.EngineBehaviourVersion + ")", "v" + latencykernel.EngineBehaviourVersion,
			latencykernel.EngineBehaviourCommit,
			"`EngineBehaviourVersion`, `EngineBehaviourCommit` in `new.go`"},
		{"Interfaces and document types: [blis-schemas](https://github.com/inference-sim/blis-schemas/tree/" +
			schemas + ")", schemas, "", "`go.mod`"},
	}
	names := map[string]string{"catalog": "Declared facts", "registry": "Coefficients"}
	for _, line := range strings.Split(string(lock), "\n") {
		f := strings.Fields(line)
		if len(f) < 5 || strings.HasPrefix(f[0], "#") {
			continue
		}
		repo := strings.TrimPrefix(f[1], "https://github.com/inference-sim/")
		pins = append(pins, pin{
			fmt.Sprintf("%s: [%s](%s/tree/%s)", names[f[0]], repo, f[1], f[3]),
			f[2], f[3], "`testdata/upstream.lock`"})
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- %s -->\n\n", generatedNote)
	b.WriteString("| What | Version | Commit | Pinned in |\n|---|---|---|---|\n")
	for _, p := range pins {
		commit := "—"
		if p.commit != "" {
			commit = "`" + p.commit[:12] + "`"
		}
		fmt.Fprintf(&b, "| %s | `%s` | %s | %s |\n", p.what, p.version, commit, p.where)
	}
	return b.Bytes(), nil
}
