#!/usr/bin/env python3
"""Generate one scenario file per deployment in the AISimulate e2e corpus.

# Why generated rather than committed by hand

There are 46 of them, and every field that matters is already stated by the corpus's own
topology record: model, gpu, precision, framework and the parallelism block. Transcribing
those by hand is how a scenario comes to describe a deployment other than the one it scores --
the previous corpus had two sweeps pointing at a single scenario file, so one of them was
scored against the wrong parallelism. Generating from the corpus makes that class of error
impossible: the file and the points it is scored against come from one record.

# What the corpus states, and what it does not

STATED, and written here: tp_size, pp_size, attention_dp_size, moe_ep_size, moe_tp_size,
framework, precision, serving, gpu, model.

NOT stated, and therefore engine defaults: max_num_seqs, max_model_len, block_size,
gpu_memory_utilization, cudagraph_mode. The comparison scores the RATIO of step times across
concurrency at a fixed deployment, so a constant cancels. Where a default could NOT cancel it
is derived from the workload instead -- max_model_len must admit the longest sequence the
workload runs, or the scenario would describe a deployment that cannot serve its own points.

# Expert parallelism

vLLM's rule (fused_moe/config.py): with EP on, each rank holds whole experts and moe_tp_size
is 1; with EP off, experts are sliced tensor-parallel and moe_tp_size equals tp_size. The
corpus states both fields, so this asserts they agree with that rule rather than assuming it.

Usage:

    python scripts/gen_aisimulate_scenarios.py testdata/measurements/aisimulate_e2e.json \
        -o testdata/aisimulate
"""

import argparse
import collections
import json
import os
import sys

COEFFICIENTS = (
    "[cost-model-primitives, cost-model-collectives, cost-model-host-overheads, "
    "cost-model-attention, cost-model-recurrent]"
)

# Artifact precision -> the engine's quantization name. bf16 means the checkpoint is served
# unquantised, which the schema spells as an absent quantization rather than a name.
QUANT = {"fp4": "nvfp4", "fp8": "fp8", "bf16": None}

# A KV cache dtype is not stated by the corpus. fp8 KV is the default for the fp8 and fp4
# arms in these frameworks; bf16 serving keeps an unquantised cache.
CACHE_DTYPE = {"fp4": "fp8", "fp8": "fp8", "bf16": "auto"}

GPUS_PER_NODE = 8


def context_length(workloads: set[str]) -> int:
    """The smallest power-of-two window that admits every workload in this deployment.

    A workload identity is "<isl>:<osl>"; a request occupies isl+osl tokens at its longest.
    Rounded up to a power of two because that is how these engines are configured, and kept
    at least 32768 so a short workload does not produce an implausibly tight window.
    """
    longest = max(sum(int(p) for p in w.split(":")) for w in workloads)
    window = 32768
    while window < longest:
        window *= 2
    return window


def emit(dep: dict, workloads: set[str], labels: set[str]) -> str:
    par = dep["parallelism"]
    tp, ep, dp = par["tp_size"], par["moe_ep_size"], par["attention_dp_size"]
    # A dense model records moe_ep_size as null: it has no expert group, which is a different
    # thing from one unsharded group (ep=1). Expert parallelism is off either way.
    expert_parallel = ep is not None and ep > 1
    ranks = tp * dp
    nodes = max(1, -(-ranks // GPUS_PER_NODE))
    quant = QUANT[dep["precision"]]
    max_len = context_length(workloads)

    lines = [
        f"# {dep['model']} on {dep['gpu']}, {dep['precision']} under {dep['framework']},",
        f"# as NVIDIA's AISimulate end-to-end accuracy artifact records this deployment.",
        "#",
        "# GENERATED by scripts/gen_aisimulate_scenarios.py from the corpus's own topology",
        "# record. Re-run after a corpus update rather than editing here.",
        "#",
        f"# Topology states: tp_size {tp}, pp_size {par['pp_size']}, attention_dp_size {dp},",
        f"# moe_ep_size {ep}, moe_tp_size {par['moe_tp_size']}. Workloads scored at this",
        f"# deployment: {', '.join(sorted(labels))}.",
        "#",
        "# max_num_seqs, block_size, gpu_memory_utilization and cudagraph_mode are engine",
        "# defaults: the comparison scores a ratio across concurrency at a fixed deployment,",
        "# so a constant cancels. max_model_len is derived from the workload instead, since a",
        "# window shorter than isl+osl would describe a deployment that cannot serve its",
        "# own points.",
        "kind: Scenario",
        f"name: {dep['scenario'][:-len('.yaml')]}",
        'engine_version: "0.29.0"',
        "",
        f"model: {dep['model']}",
        f"hardware: {dep['gpu']}",
    ]
    if nodes > 1:
        lines.append("fabric: ib-400g")
    lines += [
        f"coefficients: {COEFFICIENTS}",
        "",
        "cluster:",
        f"  nodes: {nodes}",
        f"  gpus_per_node: {GPUS_PER_NODE}",
        "",
        "pools:",
        "  - role: colocated",
        f"    nodes: {nodes}",
        "    parallel:",
        f"      tp: {tp}",
        f"      pp: {par['pp_size']}",
        f"      dp: {dp}",
        f"      enable_expert_parallel: {str(expert_parallel).lower()}",
        "    engine:",
    ]
    if quant is not None:
        lines.append(f"      quantization: {quant}")
    lines += [
        f"      cache_dtype: {CACHE_DTYPE[dep['precision']]}",
        "      block_size: 16",
        "      max_num_batched_tokens: 8192",
        "      max_num_seqs: 256",
        f"      max_model_len: {max_len}",
        "      cudagraph_mode: PIECEWISE",
        "      gpu_memory_utilization: 0.9",
    ]
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("corpus")
    ap.add_argument("-o", "--out", required=True, help="scenario directory")
    ap.add_argument("--check", action="store_true",
                    help="verify the files on disk match what would be generated")
    args = ap.parse_args()

    with open(args.corpus) as fh:
        corpus = json.load(fh)

    deps: dict[str, dict] = {}
    workloads = collections.defaultdict(set)
    labels = collections.defaultdict(set)
    for s in corpus["sweeps"]:
        name = s["scenario"]
        par = s["parallelism"]
        ep, moe_tp = par["moe_ep_size"], par["moe_tp_size"]
        # vLLM's expert-sharding rule, asserted rather than assumed. It governs how experts
        # are sharded, so it says nothing about a DENSE model, which has none: the snapshot
        # records both fields as null there and the rule is skipped rather than given a
        # default that would make it pass for the wrong reason.
        if ep is None and moe_tp is None:
            pass
        elif ep is None or moe_tp is None:
            return fail(f"{name}: moe_ep_size {ep!r} with moe_tp_size {moe_tp!r}; a "
                        f"deployment states both for an MoE model and neither for a dense "
                        f"one, so one present and one absent is a corpus error")
        elif ep > 1 and moe_tp != 1:
            return fail(f"{name}: moe_ep_size {ep} with moe_tp_size {moe_tp}; "
                        f"EP holds whole experts so moe_tp_size must be 1")
        elif ep == 1 and moe_tp != par["tp_size"]:
            return fail(f"{name}: EP off but moe_tp_size {moe_tp} != tp_size "
                        f"{par['tp_size']}; sliced experts span the TP group")
        prior = deps.get(name)
        if prior is not None and prior["parallelism"] != par:
            return fail(f"{name}: two deployments share one scenario name")
        deps[name] = s
        workloads[name].add(s["workload"])
        labels[name].add(s["label"])

    os.makedirs(args.out, exist_ok=True)
    stale = []
    for name, dep in sorted(deps.items()):
        text = emit(dep, workloads[name], labels[name])
        path = os.path.join(args.out, name)
        if args.check:
            try:
                with open(path) as fh:
                    current = fh.read()
            except FileNotFoundError:
                stale.append(f"{name} (missing)")
                continue
            if current != text:
                stale.append(name)
        else:
            with open(path, "w") as fh:
                fh.write(text)

    if args.check:
        if stale:
            print(f"{len(stale)} scenario(s) stale or missing:", file=sys.stderr)
            for n in stale:
                print(f"  {n}", file=sys.stderr)
            return 1
        print(f"checked {len(deps)} scenario(s): all current")
        return 0
    print(f"wrote {len(deps)} scenario(s) to {args.out}")
    return 0


def fail(msg: str) -> int:
    print(f"error: {msg}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
